when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler: { only_exceptions: false, collect: true  }

when@test:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler: { collect: false }
# config/routes/dev/web_profiler.yaml
    _wdt:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_wdt
